name: On The Beam
favicon: null
layout_spectrum: 0.7417
typography_spectrum: 0.66812
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#776A5A'
    - '#BF4B3C'
    - '#110E05'
    - '#D4BFAA'
    - '#743F1F'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5780076757073402
purpose: []
