name: onthebeam
favicon: null
layout_spectrum: 0.22633
typography_spectrum: 0.20022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfddd2'
    - '#1aa7c0'
    - '#4784b4'
    - '#033157'
    - '#355377'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5780076757073402
purpose: []
