name: onthebeam
favicon: null
layout_spectrum: 0.5130635350942612
typography_spectrum: 0.18780520581640303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9070410698186606
  lightness: 0.17862337525002658
  saturation: 0.1649264981970191
  rhythmicContrast: 0.5780076757073402
purpose: []
