title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.375
  brandStrength: 0.4856631
  lightness: 0.5
  brandColors:
    - '#776A5A'
    - '#BF4B3C'
    - '#110E05'
    - '#D4BFAA'
    - '#743F1F'
  rhythmicContrast: 0.5780076757073402
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: On The Beam
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.66812
layout_spectrum: 0.22742
